### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by starasoft** [NEWDCMS/NEWDCMS#1]
There is No appsetting.json and Db Files Plz Send missing Files To naumanali001@gmail.com

**Comment by eyingda** [comment]
可以发数据库文件过来吗？

**Comment by aristain7** [comment]
appsettings ? Db ?

**Comment by starasoft** [comment]
I have appsettings.json and Some Part of database 
But in this project JavaScript and CSS also missing but i am woking on it
